In [1]:
# Importing all files 
from  sklearn import datasets 
from sklearn.ensemble import GradientBoostingRegressor as Sk_Gbr
import GradientBoostingImplementation as gb
from GradientBoostingImplementation import TreeViz
import warnings
import numpy as np 
warnings.filterwarnings("ignore")

In [2]:
n_features = 5

In [3]:
gbr = gb.GradientBoostingRegressor(n_estimators=10, learning_rate=0.1, max_depth=4)

s_gbr = Sk_Gbr(n_estimators=10, learning_rate=0.1, max_depth=4)

X_vars = []
y_vars = []
betas = []
implementation_importances = []
sklearn_importances = []

for i in range(10):
    print("Iteration: ", i+1)
    X,y, beta = datasets.make_regression(n_samples=100, n_features=5, n_informative=1, noise=10, coef = True)
    X_vars.append(X)
    y_vars.append(y)
    betas.append(beta)
    gbr.fit(X,y)
    
    implementation_importances.append(gbr._get_feature_importance(X))
    s_gbr.fit(X,y)
    sklearn_importances.append(s_gbr.feature_importances_)
    

Iteration:  1
Iteration:  2
Iteration:  3
Iteration:  4
Iteration:  5
Iteration:  6
Iteration:  7
Iteration:  8
Iteration:  9
Iteration:  10


In [10]:
for importance in implementation_importances:
    print(importance)
    print(type(importance))
    print(importance.shape)

[array([array([0.15355783]), array([0.03182156]), array([0.03636869]),
       0.5711345826829464, array([0.20711734])], dtype=object), array([array([0.14625904]), array([0.07512688]), array([0.0189536]),
       0.5663930257137407, array([0.19326745])], dtype=object), array([array([0.10263467]), array([0.1099087]), array([0.06317191]),
       0.5960483113330962, array([0.12823641])], dtype=object), array([array([0.22004895]), array([0.03846252]), 0.026479621289551458,
       array([0.55277068]), array([0.16223823])], dtype=object), array([array([0.03961151]), array([0.04788853]), array([0.08354711]),
       0.6355162013696366, array([0.19343665])], dtype=object), array([array([0.08680681]), array([0.11635484]), 0.079730328403184,
       0.5268084544544686, array([0.19029956])], dtype=object), array([array([0.13640706]), array([0.07403858]), 0.04670679779669981,
       array([0.53728961]), array([0.20555795])], dtype=object), array([[0.07673441],
       [0.13661208],
       [0.12216556],

AttributeError: 'list' object has no attribute 'shape'

In [24]:
actual_importances = []
for i in range(len(implementation_importances)):
    for j in range((len(implementation_importances[i]))):
        if implementation_importances[i][j].shape == (5,):
            implementation_importances[i][j] = implementation_importances[i][j].reshape(-1,1)
    actual_importances.append(np.mean(implementation_importances[i], axis = 0))
    

In [27]:
actual_importances[0].shape

(5, 1)

In [28]:
actual_importances

[array([[array([0.12936878])],
        [array([0.09280379])],
        [array([0.07210786])],
        [array([0.53350623])],
        [array([0.17221335])]], dtype=object),
 array([[array([0.00247262])],
        [array([0.00390839])],
        [0.0010152377245788598],
        [array([0.99021221])],
        [array([0.00239155])]], dtype=object),
 array([[array([0.95874767])],
        [array([0.01238726])],
        [array([0.01014969])],
        [array([0.01009697])],
        [array([0.0086184])]], dtype=object),
 array([[array([0.04021193])],
        [0.8463544544997543],
        [array([0.02612133])],
        [array([0.05691172])],
        [array([0.03040057])]], dtype=object),
 array([[array([0.00213803])],
        [array([0.99008632])],
        [array([0.00096981])],
        [array([0.00187197])],
        [array([0.00493387])]], dtype=object),
 array([[array([0.00291305])],
        [array([0.00078083])],
        [array([0.00320064])],
        [array([0.00142396])],
        [array([0.991

In [5]:
sklearn_importances

[array([0.11446144, 0.04912429, 0.05946554, 0.63640253, 0.1405462 ]),
 array([2.95019608e-04, 2.59770848e-03, 4.64417300e-04, 9.94599223e-01,
        2.04363149e-03]),
 array([0.95922614, 0.00712849, 0.01045719, 0.01550497, 0.00768321]),
 array([0.01301638, 0.89225703, 0.01413678, 0.05754663, 0.02304317]),
 array([9.24012997e-04, 9.96206612e-01, 7.12811578e-04, 2.09838082e-04,
        1.94672488e-03]),
 array([1.07426460e-03, 8.15991401e-04, 6.63584696e-04, 1.42044922e-03,
        9.96025710e-01]),
 array([0.99252255, 0.00198013, 0.00150351, 0.00242084, 0.00157298]),
 array([0.00331636, 0.98648316, 0.00730661, 0.00289388, 0.        ]),
 array([4.27350717e-04, 2.17109870e-03, 3.71456193e-03, 1.64995090e-03,
        9.92037038e-01]),
 array([0.00330253, 0.00450762, 0.95685922, 0.02842282, 0.00690782])]